<a href="https://colab.research.google.com/github/Teja2790/Teja2790/blob/main/AI_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**VACCUM CLEANER(GENERAL)**

In [7]:
class VacuumCleaner:
    def __init__(self, location='A', status='Clean'):  # Fixed __init__ method
        self.location = location
        self.status = status

    def percept(self):
        return self.status

    def act(self, action):
        if action == 'Move Right':
            self.location = 'B'
        elif action == 'Move Left':
            self.location = 'A'
        elif action == 'Suck':
            self.status = 'Clean'

# Define the table for the table-driven agent
table = {
    ('Clean', ''): 'Move Right',
    ('Clean', 'B'): 'Move Left',
    ('Dirty', 'A'): 'Suck',
    ('Dirty', 'B'): 'Suck'
}

def table_driven_agent(percept, location):
    return table.get((percept, location), 'No')

# Main function
if __name__ == "__main__":  # Fixed __name__ check
    vacuum = VacuumCleaner()  # Initialize the vacuum cleaner
    for _ in range(5):  # Simulate 5 steps
        current_percept = vacuum.percept()  # Get the current percept
        action = table_driven_agent(current_percept, vacuum.location)  # Get the action from the table
        print(f"Percept: {current_percept}, Action: {action}")
        if action != 'No':  # If an action is defined, perform it
            vacuum.act(action)
        print(f"Location: {vacuum.location}, Status: {vacuum.status}")

Percept: Clean, Action: No
Location: A, Status: Clean
Percept: Clean, Action: No
Location: A, Status: Clean
Percept: Clean, Action: No
Location: A, Status: Clean
Percept: Clean, Action: No
Location: A, Status: Clean
Percept: Clean, Action: No
Location: A, Status: Clean


In [10]:
class VacuumCleaner:
    def __init__(self, room_matrix, start_position):
        self.room = room_matrix
        self.position = start_position
        self.rows = len(room_matrix)
        self.cols = len(room_matrix[0])

    def display_room(self):
        for row in self.room:
            print(row)
        print()

    def status(self):
        row, col = self.position
        return "Dirty" if self.room[row][col] == 1 else "Clean"

    def clean(self):
        row, col = self.position
        if self.room[row][col] == 1:
            print(f"Cleaning position: {self.position} (was Dirty)")
            self.room[row][col] = 0
        else:
            print(f"Position {self.position} is already Clean.")

    def move(self, direction):
        row, col = self.position
        if direction == "up" and row > 0:
            self.position = (row - 1, col)
        elif direction == "down" and row < self.rows - 1:
            self.position = (row + 1, col)
        elif direction == "left" and col > 0:
            self.position = (row, col - 1)
        elif direction == "right" and col < self.cols - 1:
            self.position = (row, col + 1)
        else:
            print("Invalid move or boundary reached.")
        print(f"Moved {direction} to position: {self.position} (Status: {self.status()})")

    def identify_room(self):
        row, col = self.position
        room = "Room A" if row < self.rows // 2 else "Room B"
        print(f"Position {self.position} is in {room}. (Status: {self.status()})")
        return room

    def clean_entire_room(self):
        for row in range(self.rows):
            for col in range(self.cols):
                self.position = (row, col)
                self.clean()
        print("The entire room is now clean!")

room_matrix = [
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
]

start_position = (0, 0)
vacuum = VacuumCleaner(room_matrix, start_position)

print("Initial room state:")
vacuum.display_room()

vacuum.clean_entire_room()

print("Final room state:")
vacuum.display_room()

Initial room state:
[1, 0, 1]
[0, 1, 0]
[1, 0, 1]

Cleaning position: (0, 0) (was Dirty)
Position (0, 1) is already Clean.
Cleaning position: (0, 2) (was Dirty)
Position (1, 0) is already Clean.
Cleaning position: (1, 1) (was Dirty)
Position (1, 2) is already Clean.
Cleaning position: (2, 0) (was Dirty)
Position (2, 1) is already Clean.
Cleaning position: (2, 2) (was Dirty)
The entire room is now clean!
Final room state:
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]



**VACCUM CLEANER(TABLE-DRIVEN)**

In [11]:
class CleaningAgent:
    def __init__(self):  # Fixed __init__ method
        self.table = {
            ('A', 'Dirty'): 'Suck',
            ('A', 'Clean'): 'Right',
            ('B', 'Dirty'): 'Suck',
            ('B', 'Clean'): 'Down',
            ('C', 'Dirty'): 'Suck',
            ('C', 'Clean'): 'Right',
            ('D', 'Dirty'): 'Suck',
            ('D', 'Clean'): 'Up',
        }
        self.current_room = 'A'

    def perceive(self, room_state):
        return room_state[self.current_room]

    def act(self, room_state):
        current_state = self.perceive(room_state)
        action = self.table[(self.current_room, current_state)]
        print(f"Room {self.current_room} is {current_state}. Action: {action}")
        if action == 'Suck':
            room_state[self.current_room] = 'Clean'
        else:
            self.current_room = self.move(action)

    def move(self, direction):
        moves = {
            'A': {'Right': 'B'},
            'B': {'Down': 'C', 'Left': 'A'},
            'C': {'Right': 'D', 'Up': 'B'},
            'D': {'Left': 'C'},
        }
        return moves[self.current_room][direction]

room_states = {
    'A': 'Dirty',
    'B': 'Dirty',
    'C': 'Dirty',
    'D': 'Dirty',
}

agent = CleaningAgent()

for _ in range(10):
    print(f"Current state: {room_states}")
    agent.act(room_states)
    if all(state == 'Clean' for state in room_states.values()):
        print("All rooms are clean!")
        break

Current state: {'A': 'Dirty', 'B': 'Dirty', 'C': 'Dirty', 'D': 'Dirty'}
Room A is Dirty. Action: Suck
Current state: {'A': 'Clean', 'B': 'Dirty', 'C': 'Dirty', 'D': 'Dirty'}
Room A is Clean. Action: Right
Current state: {'A': 'Clean', 'B': 'Dirty', 'C': 'Dirty', 'D': 'Dirty'}
Room B is Dirty. Action: Suck
Current state: {'A': 'Clean', 'B': 'Clean', 'C': 'Dirty', 'D': 'Dirty'}
Room B is Clean. Action: Down
Current state: {'A': 'Clean', 'B': 'Clean', 'C': 'Dirty', 'D': 'Dirty'}
Room C is Dirty. Action: Suck
Current state: {'A': 'Clean', 'B': 'Clean', 'C': 'Clean', 'D': 'Dirty'}
Room C is Clean. Action: Right
Current state: {'A': 'Clean', 'B': 'Clean', 'C': 'Clean', 'D': 'Dirty'}
Room D is Dirty. Action: Suck
All rooms are clean!


**VACCUM CLEANER(SIMPLE REFLEX)**

In [13]:
class SimpleReflexAgent:
    def __init__(self):
        self.current_room = 'A'
        self.moves = {
            'A': 'B',
            'B': 'C',
            'C': 'D',
            'D': 'A',
        }

    def perceive(self, room_states):
        return room_states[self.current_room]

    def act(self, room_states):
        room_status = self.perceive(room_states)
        if room_status == 'Dirty':
            print(f"Room {self.current_room} is Dirty. Cleaning now...")
            room_states[self.current_room] = 'Clean'
            print(f"Room {self.current_room} is now Clean.")
        else:
            print(f"Room {self.current_room} is already Clean.")

        next_room = self.moves[self.current_room]
        print(f"Moving to room {next_room}.")
        self.current_room = next_room

room_states = {
    'A': 'Dirty',
    'B': 'Dirty',
    'C': 'Dirty',
    'D': 'Dirty',
}

agent = SimpleReflexAgent()
for step in range(10):
    print(f"\nStep {step + 1}: Current room states: {room_states}")
    agent.act(room_states)
    if all(state == 'Clean' for state in room_states.values()):
        print("\nAll rooms are clean! Final state:")
        print(room_states)
        break


Step 1: Current room states: {'A': 'Dirty', 'B': 'Dirty', 'C': 'Dirty', 'D': 'Dirty'}
Room A is Dirty. Cleaning now...
Room A is now Clean.
Moving to room B.

Step 2: Current room states: {'A': 'Clean', 'B': 'Dirty', 'C': 'Dirty', 'D': 'Dirty'}
Room B is Dirty. Cleaning now...
Room B is now Clean.
Moving to room C.

Step 3: Current room states: {'A': 'Clean', 'B': 'Clean', 'C': 'Dirty', 'D': 'Dirty'}
Room C is Dirty. Cleaning now...
Room C is now Clean.
Moving to room D.

Step 4: Current room states: {'A': 'Clean', 'B': 'Clean', 'C': 'Clean', 'D': 'Dirty'}
Room D is Dirty. Cleaning now...
Room D is now Clean.
Moving to room A.

All rooms are clean! Final state:
{'A': 'Clean', 'B': 'Clean', 'C': 'Clean', 'D': 'Clean'}


**WATER JUG**

In [14]:
from collections import deque
def is_goal_state(state):

    return state[0] == 4 or state[1] == 4

def get_possible_moves(state):

    jug1, jug2 = state
    moves = []


    max_jug1 = 3
    max_jug2 = 5


    moves.append((max_jug1, jug2))
    moves.append((jug1, max_jug2))


    moves.append((0, jug2))
    moves.append((jug1, 0))


    transfer = min(jug1, max_jug2 - jug2)
    moves.append((jug1 - transfer, jug2 + transfer))


    transfer = min(jug2, max_jug1 - jug1)
    moves.append((jug1 + transfer, jug2 - transfer))

    return moves

def water_jug_problem():

    initial_state = (0, 0)
    queue = deque([initial_state])
    visited = set()
    parent_map = {initial_state: None}

    while queue:
        current_state = queue.popleft()

        if is_goal_state(current_state):

            path = []
            while current_state is not None:
                path.append(current_state)
                current_state = parent_map[current_state]
            return path[::-1]

        if current_state in visited:
            continue

        visited.add(current_state)

        for move in get_possible_moves(current_state):
            if move not in visited and move not in queue:
                queue.append(move)
                parent_map[move] = current_state

    return None


solution = water_jug_problem()
if solution:
    print("Solution path:")
    for step in solution:
        print(step)
else:
    print("No solution found.")

Solution path:
(0, 0)
(0, 5)
(3, 2)
(0, 2)
(2, 0)
(2, 5)
(3, 4)


**BFS DFS**

In [16]:
from collections import deque

class Node:
    def __init__(self, state, parent=None):  # Fixed __init__ method
        self.state = state
        self.parent = parent
        self.children = []

    def path(self):
        current = self
        path = []
        while current:
            path.append(current.state)
            current = current.parent
        return path[::-1]

def bfs(initial_state, goal_state, neighbors_func):
    root = Node(initial_state)
    queue = deque([root])
    visited = {initial_state}

    while queue:
        node = queue.popleft()

        if node.state == goal_state:
            return node.path(), root

        for neighbor in neighbors_func(node.state):
            if neighbor not in visited:
                visited.add(neighbor)
                child = Node(neighbor, node)
                node.children.append(child)
                queue.append(child)

    return None, root

def dfs(initial_state, goal_state, neighbors_func):
    root = Node(initial_state)
    stack = [root]
    visited = {initial_state}

    while stack:
        node = stack.pop()

        if node.state == goal_state:
            return node.path(), root

        for neighbor in reversed(neighbors_func(node.state)):
            if neighbor not in visited:
                visited.add(neighbor)
                child = Node(neighbor, node)
                node.children.append(child)
                stack.append(child)

    return None, root

def neighbors(state):
    graph = {
        'A': ['B', 'C'],
        'B': ['D', 'E'],
        'C': ['F'],
        'D': [],
        'E': ['F'],
        'F': []
    }
    return graph.get(state, [])

def print_tree(node, level=0):
    if node:
        print('  ' * level + node.state)
        for child in node.children:
            print_tree(child, level + 1)

initial_state = 'A'
goal_state = 'F'

print("BFS Search:")
bfs_result, bfs_root = bfs(initial_state, goal_state, neighbors)
print("BFS Path:", bfs_result)

print("\nDFS Search:")
dfs_result, dfs_root = dfs(initial_state, goal_state, neighbors)
print("DFS Path:", dfs_result)

BFS Search:
BFS Path: ['A', 'C', 'F']

DFS Search:
DFS Path: ['A', 'B', 'E', 'F']


**MONKEY BANANA(SIMPLE)**

In [18]:
from collections import deque
import numpy as np

class MonkeyBananaProblem:
    def __init__(self):  # Fixed __init__ method
        self.grid = np.zeros((3, 3), dtype=int)
        self.monkey_pos = (2, 0)
        self.banana_pos = (0, 1)
        self.chair_pos = (1, 1)
        self._initialize_grid()

    def _initialize_grid(self):
        self.grid[self.monkey_pos] = 1  # Monkey is represented by 1
        self.grid[self.banana_pos] = 2  # Banana is represented by 2
        self.grid[self.chair_pos] = 3  # Chair is represented by 3

    def get_valid_moves(self, pos):
        moves = []
        for dx, dy in [(0, 1), (1, 0), (0, -1), (-1, 0)]:  # Right, Down, Left, Up
            new_x, new_y = pos[0] + dx, pos[1] + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:  # Ensure within grid bounds
                moves.append((new_x, new_y))
        return moves

    def find_path_to_chair(self):
        return self._bfs(self.monkey_pos, self.chair_pos)

    def find_path_to_banana(self):
        return self._bfs(self.chair_pos, self.banana_pos)

    def _bfs(self, start, goal):
        queue = deque([[start]])
        visited = {start}

        while queue:
            path = queue.popleft()
            current = path[-1]

            if current == goal:
                return path

            for next_pos in self.get_valid_moves(current):
                if next_pos not in visited:
                    visited.add(next_pos)
                    queue.append(path + [next_pos])

        return []

    def solve(self):
        path_to_chair = self.find_path_to_chair()
        print("Path to chair:", path_to_chair)
        print("Moving chair under banana...")
        path_to_banana = self.find_path_to_banana()
        print("Path to banana:", path_to_banana)
        return path_to_chair + path_to_banana

problem = MonkeyBananaProblem()
print("Initial state:")
print(problem.grid)
solution = problem.solve()
print("\nComplete solution path:", solution)

Initial state:
[[0 2 0]
 [0 3 0]
 [1 0 0]]
Path to chair: [(2, 0), (2, 1), (1, 1)]
Moving chair under banana...
Path to banana: [(1, 1), (0, 1)]

Complete solution path: [(2, 0), (2, 1), (1, 1), (1, 1), (0, 1)]


**MONKEY BANANA(MULTI-AGENT)**

In [21]:
import numpy as np
from typing import Tuple, List

class MonkeyGame:
    def __init__(self, monkey1_start: Tuple[int, int], monkey2_start: Tuple[int, int], banana_pos: Tuple[int, int], chair_pos: Tuple[int, int]):  # Fixed __init__ method
        self.grid = np.zeros((3, 3), dtype=int)
        self.monkey1_pos = monkey1_start
        self.monkey2_pos = monkey2_start
        self.banana_pos = banana_pos
        self.chair_pos = chair_pos
        self._initialize_grid()

    def _initialize_grid(self):
        self.grid[self.monkey1_pos] = 1  # Monkey 1 is represented by 1
        self.grid[self.monkey2_pos] = 2  # Monkey 2 is represented by 2
        self.grid[self.banana_pos] = 3  # Banana is represented by 3
        self.grid[self.chair_pos] = 4  # Chair is represented by 4

    def get_valid_moves(self, pos: Tuple[int, int]) -> List[Tuple[int, int]]:
        moves = []
        for dx, dy in [(0, 1), (1, 0), (0, -1), (-1, 0)]:  # Right, Down, Left, Up
            new_x, new_y = pos[0] + dx, pos[1] + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:  # Ensure within grid bounds
                moves.append((new_x, new_y))
        return moves

    def manhattan_distance(self, pos1: Tuple[int, int], pos2: Tuple[int, int]) -> int:
        return abs(pos1[0] - pos2[0]) + abs(pos1[1] - pos2[1])

    def move_monkey(self, monkey_id: int) -> bool:
        current_pos = self.monkey1_pos if monkey_id == 1 else self.monkey2_pos
        moves = self.get_valid_moves(current_pos)
        best_move = min(moves, key=lambda m: self.manhattan_distance(m, self.banana_pos))
        self.grid[current_pos] = 0
        if monkey_id == 1:
            self.monkey1_pos = best_move
            self.grid[best_move] = 1
        else:
            self.monkey2_pos = best_move
            self.grid[best_move] = 2
        return best_move == self.banana_pos

    def play_game(self):
        max_moves = 10
        moves = 0
        winner = None

        while moves < max_moves and not winner:
            print(f"\nMove {moves + 1}:")
            if self.move_monkey(1):
                print(self.grid)
                winner = "Monkey 1"
                break
            print(self.grid)
            if self.move_monkey(2):
                print(self.grid)
                winner = "Monkey 2"
                break
            print(self.grid)
            moves += 1

        return winner if winner else "Draw"

def get_user_input() -> Tuple[Tuple[int, int], Tuple[int, int], Tuple[int, int], Tuple[int, int]]:
    print("Enter the starting positions for the monkeys, the banana, and the chair.")
    monkey1_start = tuple(map(int, input("Monkey 1 position (row, col): ").split(',')))
    monkey2_start = tuple(map(int, input("Monkey 2 position (row, col): ").split(',')))
    banana_pos = tuple(map(int, input("Banana position (row, col): ").split(',')))
    chair_pos = tuple(map(int, input("Chair position (row, col): ").split(',')))
    return monkey1_start, monkey2_start, banana_pos, chair_pos

monkey1_start, monkey2_start, banana_pos, chair_pos = get_user_input()
game = MonkeyGame(monkey1_start, monkey2_start, banana_pos, chair_pos)
print("Initial state:")
print(game.grid)
winner = game.play_game()
print(f"\nGame Over! Winner: {winner}")

Enter the starting positions for the monkeys, the banana, and the chair.
Monkey 1 position (row, col): 0,1
Monkey 2 position (row, col): 1,1
Banana position (row, col): 0,2
Chair position (row, col): 2,2
Initial state:
[[0 1 3]
 [0 2 0]
 [0 0 4]]

Move 1:
[[0 0 1]
 [0 2 0]
 [0 0 4]]

Game Over! Winner: Monkey 1


**8-PUZZLE GAME**

In [23]:
import heapq
from typing import List, Tuple

class PuzzleState:
    def __init__(self, board: List[List[int]], empty_tile_pos: Tuple[int, int], moves: int, parent=None):  # Fixed __init__ method
        self.board = board
        self.empty_tile_pos = empty_tile_pos
        self.moves = moves
        self.parent = parent
        self.cost = self.moves + self.manhattan_distance()

    def manhattan_distance(self) -> int:
        distance = 0
        for i in range(3):
            for j in range(3):
                if self.board[i][j] != 0:
                    x, y = divmod(self.board[i][j] - 1, 3)
                    distance += abs(x - i) + abs(y - j)
        return distance

    def is_goal(self) -> bool:
        return self.board == [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

    def get_neighbors(self) -> List['PuzzleState']:
        neighbors = []
        x, y = self.empty_tile_pos
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        for dx, dy in directions:
            new_x, new_y = x + dx, y + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:  # Ensure within grid bounds
                new_board = [row[:] for row in self.board]
                new_board[x][y], new_board[new_x][new_y] = new_board[new_x][new_y], new_board[x][y]
                neighbors.append(PuzzleState(new_board, (new_x, new_y), self.moves + 1, self))
        return neighbors

    def __lt__(self, other: 'PuzzleState') -> bool:  # Fixed method name
        return self.cost < other.cost

def print_board(board: List[List[int]]):
    for row in board:
        print(row)
    print()

def a_star_search(initial_board: List[List[int]]) -> PuzzleState:
    empty_tile_pos = next((i, j) for i in range(3) for j in range(3) if initial_board[i][j] == 0)
    start_state = PuzzleState(initial_board, empty_tile_pos, 0)
    frontier = []
    heapq.heappush(frontier, start_state)
    visited = set()

    while frontier:
        current_state = heapq.heappop(frontier)

        if current_state.is_goal():
            return current_state

        visited.add(tuple(map(tuple, current_state.board)))

        for neighbor in current_state.get_neighbors():
            if tuple(map(tuple, neighbor.board)) not in visited:
                heapq.heappush(frontier, neighbor)

    return None

def reconstruct_path(state: PuzzleState):
    path = []
    while state:
        path.append(state)
        state = state.parent
    return path[::-1]

# Initial board configuration
initial_board = [
    [8, 1, 3],
    [4, 0, 2],
    [7, 6, 5]
]

goal_state = a_star_search(initial_board)
if goal_state:
    path = reconstruct_path(goal_state)
    for state in path:
        print_board(state.board)
else:
    print("No solution found.")

[8, 1, 3]
[4, 0, 2]
[7, 6, 5]

[8, 1, 3]
[4, 2, 0]
[7, 6, 5]

[8, 1, 3]
[4, 2, 5]
[7, 6, 0]

[8, 1, 3]
[4, 2, 5]
[7, 0, 6]

[8, 1, 3]
[4, 2, 5]
[0, 7, 6]

[8, 1, 3]
[0, 2, 5]
[4, 7, 6]

[0, 1, 3]
[8, 2, 5]
[4, 7, 6]

[1, 0, 3]
[8, 2, 5]
[4, 7, 6]

[1, 2, 3]
[8, 0, 5]
[4, 7, 6]

[1, 2, 3]
[0, 8, 5]
[4, 7, 6]

[1, 2, 3]
[4, 8, 5]
[0, 7, 6]

[1, 2, 3]
[4, 8, 5]
[7, 0, 6]

[1, 2, 3]
[4, 0, 5]
[7, 8, 6]

[1, 2, 3]
[4, 5, 0]
[7, 8, 6]

[1, 2, 3]
[4, 5, 6]
[7, 8, 0]



**HANGMAN GAME**

In [24]:
import random
from collections import Counter


WORD_LIST = ["python", "intelligent", "machine", "learning", "artificial", "language", "model"]

def display_hangman(attempts):
    stages = [
        """
           --------
           |      |
           |      O
           |     \|/
           |      |
           |     / \\
        """,
        """
           --------
           |      |
           |      O
           |     \|/
           |      |
           |     /
        """,
        """
           --------
           |      |
           |      O
           |     \|/
           |      |
           |
        """,
        """
           --------
           |      |
           |      O
           |     \|
           |      |
           |
        """,
        """
           --------
           |      |
           |      O
           |      |
           |      |
           |
        """,
        """
           --------
           |      |
           |      O
           |
           |
           |
        """,
        """
           --------
           |      |
           |
           |
           |
           |
        """
    ]
    print(stages[attempts])

def play_hangman(secret_word):
    """ Modified Hangman where Player 1 reveals a letter, and Player 2 guesses its position automatically. """
    pattern = ["_"] * len(secret_word)
    attempts = 6

    print("\nStarting Hangman Game!")
    print("Current Word: ", " ".join(pattern))

    while "_" in pattern and attempts > 0:
        display_hangman(attempts)


        remaining_letters = [l for l in secret_word if l not in pattern]
        if not remaining_letters:
            break

        revealed_letter = random.choice(remaining_letters)
        print(f"Player 1 Reveals Letter: {revealed_letter}")


        possible_positions = [i for i, l in enumerate(secret_word) if l == revealed_letter and pattern[i] == "_"]
        if possible_positions:
            guessed_position = random.choice(possible_positions)
            pattern[guessed_position] = revealed_letter
            print(f"Player 2 guessed position {guessed_position + 1} correctly!")
        else:
            attempts -= 1
            print("Wrong Position! Remaining attempts:", attempts)

    display_hangman(attempts)
    if "_" not in pattern:
        print("Player 2 Wins! Word is:", "".join(pattern))
    else:
        print("Player 1 Wins! Player 2 couldn't guess all positions correctly.")


secret_word = random.choice(WORD_LIST)
play_hangman(secret_word)


Starting Hangman Game!
Current Word:  _ _ _ _ _ _ _

           --------
           |      |
           |
           |
           |
           |
        
Player 1 Reveals Letter: a
Player 2 guessed position 2 correctly!

           --------
           |      |
           |
           |
           |
           |
        
Player 1 Reveals Letter: m
Player 2 guessed position 1 correctly!

           --------
           |      |
           |
           |
           |
           |
        
Player 1 Reveals Letter: h
Player 2 guessed position 4 correctly!

           --------
           |      |
           |
           |
           |
           |
        
Player 1 Reveals Letter: n
Player 2 guessed position 6 correctly!

           --------
           |      |
           |
           |
           |
           |
        
Player 1 Reveals Letter: c
Player 2 guessed position 3 correctly!

           --------
           |      |
           |
           |
           |
           |
        
Playe

**8-QUEENS PROBLEM**

In [26]:
def print_board(board):
    for row in board:
        print(" ".join(row))
    print("\n")

def is_safe(board, row, col, n):
    for i in range(row):
        if board[i][col] == "Q":
            return False
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == "Q":
            return False
    for i, j in zip(range(row, -1, -1), range(col, n)):
        if board[i][j] == "Q":
            return False
    return True

def solve_n_queens(board, row, n):
    if row == n:
        print_board(board)
        return True
    res = False
    for col in range(n):
        if is_safe(board, row, col, n):
            board[row][col] = "Q"
            res = solve_n_queens(board, row + 1, n) or res
            board[row][col] = "."
    return res

def main():
    n = 8
    board = [["." for _ in range(n)] for _ in range(n)]
    if not solve_n_queens(board, 0, n):
        print("No solution exists")
    else:
        print("Solutions found!")

if __name__ == "__main__":  # Fixed __name__ and __main__
    main()

Q . . . . . . .
. . . . Q . . .
. . . . . . . Q
. . . . . Q . .
. . Q . . . . .
. . . . . . Q .
. Q . . . . . .
. . . Q . . . .


Q . . . . . . .
. . . . . Q . .
. . . . . . . Q
. . Q . . . . .
. . . . . . Q .
. . . Q . . . .
. Q . . . . . .
. . . . Q . . .


Q . . . . . . .
. . . . . . Q .
. . . Q . . . .
. . . . . Q . .
. . . . . . . Q
. Q . . . . . .
. . . . Q . . .
. . Q . . . . .


Q . . . . . . .
. . . . . . Q .
. . . . Q . . .
. . . . . . . Q
. Q . . . . . .
. . . Q . . . .
. . . . . Q . .
. . Q . . . . .


. Q . . . . . .
. . . Q . . . .
. . . . . Q . .
. . . . . . . Q
. . Q . . . . .
Q . . . . . . .
. . . . . . Q .
. . . . Q . . .


. Q . . . . . .
. . . . Q . . .
. . . . . . Q .
Q . . . . . . .
. . Q . . . . .
. . . . . . . Q
. . . . . Q . .
. . . Q . . . .


. Q . . . . . .
. . . . Q . . .
. . . . . . Q .
. . . Q . . . .
Q . . . . . . .
. . . . . . . Q
. . . . . Q . .
. . Q . . . . .


. Q . . . . . .
. . . . . Q . .
Q . . . . . . .
. . . . . . Q .
. . . Q . . . .
. . . . . 